# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:

    providers:
        chain_provider:
            chain:
                providers: [fos_userbundle]
        fos_userbundle:
            id: fos_user.user_provider.username_email

    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_BETATESTER_LEVEL_0: ROLE_USER
        ROLE_ADMIN:              ROLE_USER
        ROLE_SUPER_ADMIN:        ROLE_ADMIN

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            form_login:
                                                # We use route names instead of paths because that honors the _locale path segment
                provider:                       fos_userbundle
                login_path:                     fos_user_security_login
                check_path:                     fos_user_security_check
                default_target_path:            remotedesktops.index
                always_use_default_target_path: true
                remember_me: true
            remember_me:
                secret:   "%secret%"
                lifetime: 31536000 # 365 days in seconds
                path:     /
            logout:
                path:   fos_user_security_logout
                target: logout_successful
            anonymous: true

    access_control:
        - { path: ^/[a-z][a-z]/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/[a-z][a-z]/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/[a-z][a-z]/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/[a-z][a-z]/administration, role: ROLE_ADMIN }
        - { path: sgx_files, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: updatettl, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/[a-z][a-z]/remoteDesktops, role: ROLE_USER }
        - { path: ^/[a-z][a-z]/accountMovements, role: ROLE_USER }
