homepage:
    path:     /
    defaults: { _controller: AppBundle:Default:index }
    methods:  [GET]

about.howBillingWorks:
    path:     /about/how-billing-works
    defaults: { _controller: AppBundle:About:howBillingWorks }
    methods:  [GET]

logout_successful:
    path:     /logout-successful
    defaults: { _controller: AppBundle:Default:logoutSuccessful }
    methods:  [GET]

remotedesktops.index:
    path:     /remoteDesktops/
    defaults: { _controller: AppBundle:RemoteDesktop:index }
    methods:  [GET]

remotedesktops.new:
    path:     /remoteDesktops/new
    defaults: { _controller: AppBundle:RemoteDesktop:new }
    methods:  [GET, POST]

remotedesktops.status:
    path:     /remoteDesktops/{remoteDesktop}/status
    defaults: { _controller: AppBundle:RemoteDesktop:status }
    methods:  [GET]

remotedesktops.stop:
    path:     /remoteDesktops/{remoteDesktop}/stop
    defaults: { _controller: AppBundle:RemoteDesktop:stop }
    methods:  [GET]

remotedesktops.start:
    path:     /remoteDesktops/{remoteDesktop}/start
    defaults: { _controller: AppBundle:RemoteDesktop:start }
    methods:  [GET]

remotedesktops.terminate:
    path:     /remoteDesktops/{remoteDesktop}/terminate
    defaults: { _controller: AppBundle:RemoteDesktop:terminate }
    methods:  [GET]

remotedesktops.updateScheduleForStopAt:
    path:     /remoteDesktops/{remoteDesktop}/updateScheduleForStopAt/{duration}
    defaults: { _controller: AppBundle:RemoteDesktop:updateScheduleForStopAt }
    methods:  [GET]

remotedesktops.sgx_files:
    path:     /remoteDesktops/{remoteDesktop}/{remoteDesktopIdHash}/{width}/{height}/sgx_files/{tag}.sgx
    defaults: { _controller: AppBundle:RemoteDesktop:serveSgxFile }
    methods:  [GET]

remotedesktops.updatettl:
    path:     /remoteDesktops/{remoteDesktop}/{remoteDesktopIdHash}/{width}/{height}/updatettl/{tag}
    defaults: { _controller: AppBundle:RemoteDesktop:serveSgxFile }
    methods:  [GET]

cloudinstances.new:
    path:     /remoteDesktops/{remoteDesktop}/cloudInstances/new
    defaults: { _controller: AppBundle:CloudInstance:new }
    methods:  [GET, POST]

cloudinstances.remainingTtl:
    path:     /cloudInstances/remainingTtl
    defaults: { _controller: AppBundle:CloudInstance:remainingTtl }
    methods:  [GET]

accountmovements.index:
    path:     /accountMovements/
    defaults: { _controller: AppBundle:AccountMovement:index }
    methods:  [GET]

accountmovements.new:
    path:     /accountMovements/newDeposit
    defaults: { _controller: AppBundle:AccountMovement:newDeposit }
    methods:  [GET, POST]

payment.new:
    path:     /accountMovements/{accountMovement}/payment/new
    defaults: { _controller: AppBundle:Payment:new }
    methods:  [GET, POST]

payment.finish:
    path:     /accountMovements/{accountMovement}/payment/finish
    defaults: { _controller: AppBundle:Payment:finish }
    methods:  [GET]

payment.cancel:
    path:     /accountMovements/{accountMovement}/payment/cancel
    defaults: { _controller: AppBundle:Payment:cancel }
    methods:  [GET]
