homepage:
    path:     /
    defaults: { _controller: AppBundle:Default:index }
    methods:  [GET]

remotedesktop_new:
    path:     /remoteDesktops/new
    defaults: { _controller: AppBundle:RemoteDesktop:new }
    methods:  [GET, POST]
