homepage:
    path:     /
    defaults: { _controller: AppBundle:Default:index }
    methods:  [GET]

logout_successful:
    path:     /logout-successful
    defaults: { _controller: AppBundle:Default:logoutSuccessful }
    methods:  [GET]

remotedesktops.index:
    path:     /remoteDesktops/
    defaults: { _controller: AppBundle:RemoteDesktop:index }
    methods:  [GET]

remotedesktops.new:
    path:     /remoteDesktops/new
    defaults: { _controller: AppBundle:RemoteDesktop:new }
    methods:  [GET, POST]

remotedesktops.stop:
    path:     /remoteDesktops/{remoteDesktop}/stop
    defaults: { _controller: AppBundle:RemoteDesktop:stop }
    methods:  [GET]

remotedesktops.start:
    path:     /remoteDesktops/{remoteDesktop}/start
    defaults: { _controller: AppBundle:RemoteDesktop:start }
    methods:  [GET]

remotedesktops.terminate:
    path:     /remoteDesktops/{remoteDesktop}/terminate
    defaults: { _controller: AppBundle:RemoteDesktop:terminate }
    methods:  [GET]

remotedesktops.sgx_files:
    path:     /remoteDesktops/{remoteDesktop}/sgx_files/{tag}.sgx
    defaults: { _controller: AppBundle:RemoteDesktop:serveSgxFile }
    methods:  [GET]

remotedesktops.updatettl:
    path:     /remoteDesktops/{remoteDesktop}/updatettl/{tag}
    defaults: { _controller: AppBundle:RemoteDesktop:serveSgxFile }
    methods:  [GET]

cloudinstances.new:
    path:     /remoteDesktops/{remoteDesktop}/cloudInstances/new
    defaults: { _controller: AppBundle:CloudInstance:new }
    methods:  [GET, POST]

accountmovements.new:
    path:     /accountMovements/newDeposit
    defaults: { _controller: AppBundle:AccountMovement:newDeposit }
    methods:  [GET, POST]

payment.new:
    path:     /accountMovements/{accountMovement}/payment/new
    defaults: { _controller: AppBundle:Payment:new }
    methods:  [GET, POST]

payment.finish:
    path:     /accountMovements/{accountMovement}/payment/finish
    defaults: { _controller: AppBundle:Payment:finish }
    methods:  [GET]

payment.cancel:
    path:     /accountMovements/{accountMovement}/payment/cancel
    defaults: { _controller: AppBundle:Payment:cancel }
    methods:  [GET]
