homepage:
    path:     /
    defaults: { _controller: AppBundle:Default:index }
    methods:  [GET]

logout_successful:
    path:     /logout-successful
    defaults: { _controller: AppBundle:Default:logoutSuccessful }
    methods:  [GET]

remotedesktops.index:
    path:     /remoteDesktops/
    defaults: { _controller: AppBundle:RemoteDesktop:index }
    methods:  [GET]

remotedesktops.new:
    path:     /remoteDesktops/new
    defaults: { _controller: AppBundle:RemoteDesktop:new }
    methods:  [GET, POST]


remotedesktops.stop:
    path:     /remoteDesktops/{remoteDesktop}/stop
    defaults: { _controller: AppBundle:RemoteDesktop:new }
    methods:  [GET]

cloudinstances.new:
    path:     /remoteDesktops/{remoteDesktop}/cloudInstances/new
    defaults: { _controller: AppBundle:CloudInstance:new }
    methods:  [GET, POST]
