homepage:
    path:     /
    defaults: { _controller: AppBundle:Default:index }
    methods:  [GET]

remotedesktops.index:
    path:     /remoteDesktops/
    defaults: { _controller: AppBundle:RemoteDesktop:index }
    methods:  [GET]

remotedesktops.new:
    path:     /remoteDesktops/new
    defaults: { _controller: AppBundle:RemoteDesktop:new }
    methods:  [GET, POST]

