homepage:
    path:     /
    defaults: { _controller: AppBundle:Default:index }
    methods:  [GET]

logout_successful:
    path:     /logout-successful
    defaults: { _controller: AppBundle:Default:logoutSuccessful }
    methods:  [GET]

remotedesktops.index:
    path:     /remoteDesktops/
    defaults: { _controller: AppBundle:RemoteDesktop:index }
    methods:  [GET]

remotedesktops.new:
    path:     /remoteDesktops/new
    defaults: { _controller: AppBundle:RemoteDesktop:new }
    methods:  [GET, POST]

remotedesktops.stop:
    path:     /remoteDesktops/{remoteDesktop}/stop
    defaults: { _controller: AppBundle:RemoteDesktop:stop }
    methods:  [GET]

remotedesktops.start:
    path:     /remoteDesktops/{remoteDesktop}/start
    defaults: { _controller: AppBundle:RemoteDesktop:start }
    methods:  [GET]

remotedesktops.terminate:
    path:     /remoteDesktops/{remoteDesktop}/terminate
    defaults: { _controller: AppBundle:RemoteDesktop:terminate }
    methods:  [GET]

cloudinstances.new:
    path:     /remoteDesktops/{remoteDesktop}/cloudInstances/new
    defaults: { _controller: AppBundle:CloudInstance:new }
    methods:  [GET, POST]

accountmovement.new:
    path:     /accountMovement/newDeposit
    defaults: { _controller: AppBundle:AccountMovement:newDeposit }
    methods:  [GET, POST]

payment.new:
    path:     /accountMovement/{accountMovement}/payment/new
    defaults: { _controller: AppBundle:Payment:new }
    methods:  [GET, POST]

payment.success:
    path:     /accountMovement/{accountMovement}/payment/success
    defaults: { _controller: AppBundle:Payment:success }
    methods:  [GET]
